# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gab < Formula
  desc "Github Action Badge Generator"
  homepage "https://github.com/abtris/ga-badge"
  version "0.2.0"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/abtris/ga-badge/releases/download/v0.2.0/gab_0.2.0_Darwin_x86_64.tar.gz"
    sha256 "ebd4323f6edd840424087deeb96bb274596bbe6a4bc7d2fdfef7322936d69e7f"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/abtris/ga-badge/releases/download/v0.2.0/gab_0.2.0_Darwin_arm64.tar.gz"
    sha256 "dbb9936aa2c860a753babb79aa5ad0d205e7843f3d13b77350dbd229794a5555"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/abtris/ga-badge/releases/download/v0.2.0/gab_0.2.0_Linux_x86_64.tar.gz"
    sha256 "cf9db37dffafb1eda94c98db449d0305ed24772312a726cea2c7c51803d7471d"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/abtris/ga-badge/releases/download/v0.2.0/gab_0.2.0_Linux_arm64.tar.gz"
    sha256 "6137828b907911ba042f643e60c85233ea2893e3a5b4183cb4db4aef59519729"
  end

  def install
    bin.install "gab"
  end
end
