# This file was generated by GoReleaser. DO NOT EDIT.
cask "mqw" do
  version "1.0.0"

  on_macos do
    on_arm do
      sha256 "457ff769849bd421194f40e981e9121af35310bc6926939001164d1850a37750"
      url "https://github.com/abtris/github-merge-queue-watcher/releases/download/v#{version}/mqw_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "49418b7258f4adc1f40fb184d319c32926fb0888133ef9580cb33448f3c93b6b"
      url "https://github.com/abtris/github-merge-queue-watcher/releases/download/v#{version}/mqw_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a5c39b4301dcc0c3777e51d6c6cfdc2fc9ed23f5ba68125c16cedfe706bb8c9e"
      url "https://github.com/abtris/github-merge-queue-watcher/releases/download/v#{version}/mqw_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "827ffa0447ec27ed4855ca8e8c4c6fc87a799844f98cc076b55bd901b6064e14"
      url "https://github.com/abtris/github-merge-queue-watcher/releases/download/v#{version}/mqw_#{version}_linux_amd64.tar.gz"
    end
  end

  name "mqw"
  desc "Terminal dashboard for moving your pull requests through a GitHub merge queue"
  homepage "https://github.com/abtris/github-merge-queue-watcher"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "gh",
    ]

  binary "mqw"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mqw"]
    end
  end

  uninstall delete: [
      "#{staged_path}/mqw",
    ]

  # No zap stanza required

  caveats <<~EOS
    mqw needs the gh CLI authenticated:
      gh auth login

    Optionally set a default repo so plain `mqw` just works:
      mkdir -p ~/.config/mqw && mqw --print-config > ~/.config/mqw/config.toml
  EOS
end
