# This file was generated by GoReleaser. DO NOT EDIT.
cask "mqw" do
  version "1.0.2"

  on_macos do
    on_arm do
      sha256 "667e7e4e6a5893dfdda3070d98ff3750ffee8621690988121c24a45eb76c3e5b"
      url "https://github.com/abtris/mqw/releases/download/v#{version}/mqw_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "fe28aa6043ec8dc157054bd1039d371310306b458e15852b9fffdb4a395a1673"
      url "https://github.com/abtris/mqw/releases/download/v#{version}/mqw_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "619eff4eea85827bcb843e8e3337eb7a8e87dbb5554d8d9d9bc0c07a30f75f19"
      url "https://github.com/abtris/mqw/releases/download/v#{version}/mqw_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "89dc48b9bf9a98aa5d2e8cb42e007bd0493aec0b5383bc58e88a6b670eb4564d"
      url "https://github.com/abtris/mqw/releases/download/v#{version}/mqw_#{version}_linux_amd64.tar.gz"
    end
  end

  name "mqw"
  desc "Terminal dashboard for moving your pull requests through a GitHub merge queue"
  homepage "https://github.com/abtris/mqw"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "gh",
    ]

  binary "mqw"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mqw"]
    end
  end

  uninstall delete: [
      "#{staged_path}/mqw",
    ]

  # No zap stanza required

  caveats <<~EOS
    mqw needs the gh CLI authenticated:
      gh auth login

    Optionally set a default repo so plain `mqw` just works:
      mkdir -p ~/.config/mqw && mqw --print-config > ~/.config/mqw/config.toml
  EOS
end
