# This file was generated by GoReleaser. DO NOT EDIT.
cask "mqw" do
  version "1.0.1"

  on_macos do
    on_arm do
      sha256 "793a27401bfeccf4b82b424f4b9bd27ca1d0927a79ed6d94a62d8688d560f791"
      url "https://github.com/abtris/mqw/releases/download/v#{version}/mqw_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4febfc6a3741d0b7e299f8abd56bff70286d4c631b545a6b77879b07edadfe08"
      url "https://github.com/abtris/mqw/releases/download/v#{version}/mqw_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7acdb8ad466c290bc6df2933ea617dd0bc4044a4e610a2201400031faaa5053a"
      url "https://github.com/abtris/mqw/releases/download/v#{version}/mqw_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9764afb9b3a6641473f408901674f0d7e4ef31f16047dd9276263dd8f10771c5"
      url "https://github.com/abtris/mqw/releases/download/v#{version}/mqw_#{version}_linux_amd64.tar.gz"
    end
  end

  name "mqw"
  desc "Terminal dashboard for moving your pull requests through a GitHub merge queue"
  homepage "https://github.com/abtris/mqw"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "gh",
    ]

  binary "mqw"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mqw"]
    end
  end

  uninstall delete: [
      "#{staged_path}/mqw",
    ]

  # No zap stanza required

  caveats <<~EOS
    mqw needs the gh CLI authenticated:
      gh auth login

    Optionally set a default repo so plain `mqw` just works:
      mkdir -p ~/.config/mqw && mqw --print-config > ~/.config/mqw/config.toml
  EOS
end
