# This file was generated by GoReleaser. DO NOT EDIT.
cask "zotero-mcp-go-server" do
  version "1.1.0"

  on_macos do
    on_intel do
      url "https://github.com/abtris/zotero-mcp-go-server/releases/download/v#{version}/zotero-mcp-go-server_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/abtris/zotero-mcp-go-server"
      sha256 "79f8a871d9d90566f3032a274d10f4d3f8c0efb5f91d2b67a2708290a8ecfc59"
    end
    on_arm do
      url "https://github.com/abtris/zotero-mcp-go-server/releases/download/v#{version}/zotero-mcp-go-server_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/abtris/zotero-mcp-go-server"
      sha256 "95c73823e9c0c402edc8d468d2f8b460e6c24e53a1f0e8889d6037ca8860c8bb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/abtris/zotero-mcp-go-server/releases/download/v#{version}/zotero-mcp-go-server_#{version}_linux_amd64.tar.gz",
        verified: "github.com/abtris/zotero-mcp-go-server"
      sha256 "bdefcbb6fd87c100321bf2ba3fb5cd5501aeda5347aadab7c74014e4f1cf5a8f"
    end
    on_arm do
      url "https://github.com/abtris/zotero-mcp-go-server/releases/download/v#{version}/zotero-mcp-go-server_#{version}_linux_arm64.tar.gz",
        verified: "github.com/abtris/zotero-mcp-go-server"
      sha256 "b93c85f1059ca507a8d3053f50b35e5180cfbe54e79a6df363fa47335fbe4027"
    end
  end

  name "zotero-mcp-go-server"
  desc "MCP server for Zotero, written in Go"
  homepage "https://github.com/abtris/zotero-mcp-go-server"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zotero-mcp-go-server"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/zotero-mcp-go-server"]
    end
  end

  # No zap stanza required

end
