# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WorktreeUtil < Formula
  desc "A simple TUI for managing Git worktrees"
  homepage "https://github.com/abtris/worktree-util"
  version "0.5.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abtris/worktree-util/releases/download/v0.5.3/worktree-util_0.5.3_Darwin_x86_64.tar.gz"
      sha256 "9e5898946cbf520a1f09bbb539450ecc7e38762b2b06ecb6fe4124804e913004"

      def install
        bin.install "worktree-util"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abtris/worktree-util/releases/download/v0.5.3/worktree-util_0.5.3_Darwin_arm64.tar.gz"
      sha256 "e699fa062fe4c52a1dfe0ec329e7656ef119af34f5c6fb99f906301ff7c7d978"

      def install
        bin.install "worktree-util"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abtris/worktree-util/releases/download/v0.5.3/worktree-util_0.5.3_Linux_x86_64.tar.gz"
      sha256 "c6bd4ee5ad64fa9462a4d5cfb41f9b796162c76387cc8098f8e04ca6da111cef"
      def install
        bin.install "worktree-util"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abtris/worktree-util/releases/download/v0.5.3/worktree-util_0.5.3_Linux_arm64.tar.gz"
      sha256 "0faffcd1537e00290dd6e4644121f6a6ea9c641ff882dbd8093284aedfbf3d32"
      def install
        bin.install "worktree-util"
      end
    end
  end

  test do
    system "#{bin}/worktree-util", "--version"
  end
end
