# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WorktreeUtil < Formula
  desc "A simple TUI for managing Git worktrees"
  homepage "https://github.com/abtris/worktree-util"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abtris/worktree-util/releases/download/v0.4.0/worktree-util_0.4.0_Darwin_x86_64.tar.gz"
      sha256 "9aab0e49cb0ad17441fea374a7c06caed9aaecc19b0df46f2f1901abf6421128"

      def install
        bin.install "worktree-util"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abtris/worktree-util/releases/download/v0.4.0/worktree-util_0.4.0_Darwin_arm64.tar.gz"
      sha256 "a65f94e16274b1923d761294c6ce880a5dc450e6f83168ab415f461b878f2ad4"

      def install
        bin.install "worktree-util"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abtris/worktree-util/releases/download/v0.4.0/worktree-util_0.4.0_Linux_x86_64.tar.gz"
      sha256 "79b9ad2f231ec1703333b694e9ccba984d5bc97a9d0837f77ab00ede5b9cc1aa"
      def install
        bin.install "worktree-util"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abtris/worktree-util/releases/download/v0.4.0/worktree-util_0.4.0_Linux_arm64.tar.gz"
      sha256 "75ddb8e30158e95b33ef2afc99b2dbca92793fe4d60d23999c479343945c431a"
      def install
        bin.install "worktree-util"
      end
    end
  end

  test do
    system "#{bin}/worktree-util", "--version"
  end
end
