# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WorktreeUtil < Formula
  desc "A simple TUI for managing Git worktrees"
  homepage "https://github.com/abtris/worktree-util"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abtris/worktree-util/releases/download/v0.3.0/worktree-util_0.3.0_Darwin_x86_64.tar.gz"
      sha256 "2e560ece48baf1ab39deb18f8083f439fd0f0619f192f10aeaebb76908af9119"

      def install
        bin.install "worktree-util"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abtris/worktree-util/releases/download/v0.3.0/worktree-util_0.3.0_Darwin_arm64.tar.gz"
      sha256 "d78de83298cdd287eee1d68027eab433127e28fb75d8729c6df637fad1ac6c5e"

      def install
        bin.install "worktree-util"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abtris/worktree-util/releases/download/v0.3.0/worktree-util_0.3.0_Linux_x86_64.tar.gz"
      sha256 "9508d745800683b36bbc887415645d8557f38fa5308f267bb2df4d8baecbb8b9"
      def install
        bin.install "worktree-util"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abtris/worktree-util/releases/download/v0.3.0/worktree-util_0.3.0_Linux_arm64.tar.gz"
      sha256 "492dbdc22fd13dc14e0d03927e5066fabb192b0a615c5d2453bff0948a347c70"
      def install
        bin.install "worktree-util"
      end
    end
  end

  test do
    system "#{bin}/worktree-util", "--version"
  end
end
