# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZoteroMcpGoServer < Formula
  desc "MCP server for Zotero, written in Go"
  homepage "https://github.com/abtris/zotero-mcp-go-server"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abtris/zotero-mcp-go-server/releases/download/v1.0.0/zotero-mcp-go-server_1.0.0_darwin_amd64.tar.gz"
      sha256 "c24e6720c4086e77e52cabc4dab429cac410fdfd32dfc2dfab63346b877bc70e"

      define_method(:install) do
        bin.install "zotero-mcp-go-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abtris/zotero-mcp-go-server/releases/download/v1.0.0/zotero-mcp-go-server_1.0.0_darwin_arm64.tar.gz"
      sha256 "b5079e7264aef19ceee170f7456fc039cebdb047e90cf2f5ce71297327fc7065"

      define_method(:install) do
        bin.install "zotero-mcp-go-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abtris/zotero-mcp-go-server/releases/download/v1.0.0/zotero-mcp-go-server_1.0.0_linux_amd64.tar.gz"
      sha256 "5a290ad563ef6a7fa8b0708b37a05349308a57b1eba4c67dff5aee94269090c6"
      define_method(:install) do
        bin.install "zotero-mcp-go-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abtris/zotero-mcp-go-server/releases/download/v1.0.0/zotero-mcp-go-server_1.0.0_linux_arm64.tar.gz"
      sha256 "42b2e96a20008f7504f2e56c283f96b9557e84a9929a41713b97af5805e39f50"
      define_method(:install) do
        bin.install "zotero-mcp-go-server"
      end
    end
  end

  test do
    system "#{bin}/zotero-mcp-go-server 2>&1 || true"
  end
end
